#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : exfat-utils
Version  : 1.3.0
Release  : 1
URL      : https://github.com/relan/exfat/releases/download/v1.3.0/exfat-utils-1.3.0.tar.gz
Source0  : https://github.com/relan/exfat/releases/download/v1.3.0/exfat-utils-1.3.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: exfat-utils-bin = %{version}-%{release}
Requires: exfat-utils-license = %{version}-%{release}
Requires: exfat-utils-man = %{version}-%{release}

%description
About
-----
This project aims to provide a full-featured [exFAT][1] file system implementation for Unix-like systems. It consists of a [FUSE][2] module (fuse-exfat) and a set of utilities (exfat-utils).

%package bin
Summary: bin components for the exfat-utils package.
Group: Binaries
Requires: exfat-utils-license = %{version}-%{release}

%description bin
bin components for the exfat-utils package.


%package license
Summary: license components for the exfat-utils package.
Group: Default

%description license
license components for the exfat-utils package.


%package man
Summary: man components for the exfat-utils package.
Group: Default

%description man
man components for the exfat-utils package.


%prep
%setup -q -n exfat-utils-1.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571085087
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1571085087
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/exfat-utils
cp %{_builddir}/exfat-utils-1.3.0/COPYING %{buildroot}/usr/share/package-licenses/exfat-utils/4cc77b90af91e615a64ae04893fdffa7939db84c
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dumpexfat
/usr/bin/exfatfsck
/usr/bin/exfatlabel
/usr/bin/fsck.exfat
/usr/bin/mkexfatfs
/usr/bin/mkfs.exfat

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/exfat-utils/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/dumpexfat.8
/usr/share/man/man8/exfatfsck.8
/usr/share/man/man8/exfatlabel.8
/usr/share/man/man8/mkexfatfs.8
